#!/bin/sh
./forever -a -o ./data/skolajs.log -e ./data/skolajs-err.log -l ./data/forever.log stop server.js
./forever -a -o ./data/skolajs.log -e ./data/skolajs-err.log -l ./data/forever.log start server.js
